$term = foot
$file = $term yazi
$browser = brave

$screenshot_output = -o ~/Pictures/Screenshots/ -f "$(date '+%Y-%m-%d %H-%M-%S').png"

$s = ~/.config/hypr/scripts
$osd = $s/osd.sh

$f = [float; size (monitor_w*0.80) (monitor_h*0.75)]

# source configs
source = ./configs/env.conf
source = ./configs/layout.conf
source = ./configs/input.conf
source = ./configs/bind.conf
source = ./configs/appearance.conf
source = ./configs/autostart.conf

# nwg-displays
source = ./monitors.conf
source = ./workspaces.conf

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  disable_splash_rendering = true
  disable_hyprland_logo = true
}
