general {
  gaps_in = 5
  gaps_out = 10

  border_size = 0
  col.active_border = rgba(eadab1ff)
  col.inactive_border = rgba(918273ff)

  allow_tearing = false
}

decoration {
  rounding = 0
  rounding_power = 0

  active_opacity = 0.9
  inactive_opacity = 0.8

  shadow {
    enabled = true
    range = 10
    render_power = 6
    color = rgba(1a1a1aee)
  }

  blur {
    enabled = true
    size = 1
    passes = 3

    vibrancy = 0.1696
  }
}

group {
  groupbar {
    font_size = 14
    font_weight_active = bold

    rounding = 0

    text_color = rgba(eadab1ff)
    text_color_inactive = rgba(665c55ff)
    text_color_locked_active = rgba(fabc33ff)
    text_color_locked_inactive = rgba(665c55ff)

    col.active = rgba(eadab1ff)
    col.inactive = rgba(665c55ff)
    col.locked_active = rgba(fabc33ff)
    col.locked_inactive = rgba(665c55ff)
  }
}

animations {
  enabled = false
}

cursor {
  inactive_timeout = 1
  hide_on_key_press = true
  zoom_detached_camera = false
}

misc {
    font_family = CaskaydiaCoveNerdFont
  }
