binds {
  scroll_event_delay = 100
}

gesture = 3, horizontal, workspace

# APPS
bindue = Super, Return, exec, $term
bindue = Super, E,      exec, $file

# WINDOW
bindue = Super, Q, killactive,
bindu  = , F11,     fullscreen, 0

# SYSTEM
binduel = Super, Space, exec, $s/kbl.sh

### APPS
bindu = Super, A, submap, apps
submap = apps, reset

bind = ,      F, exec, $term
bind = ,      E, exec, $file
bind = ,      D, exec, vesktop
bind = ,      B, exec, $browser
bind = Shift, B, exec, $f $term bluetui
bind = Shift, S, exec, flatpak run org.vinegarhq.Sober
bind = ,      O, exec, obsidian
bind = ,      N, exec, $term nvim
bind = ,      T, exec, $f $term btop
bind = ,      M, exec, $f $term pulsemixer
bind = ,      C, exec, hyprpicker -a

bind = , Escape, submap, reset
submap = reset
### END APPS

### WINDOW
bindu = Super, W, submap, window
submap = window, reset

bind = , Space,   togglefloating,
bind = , F,       fullscreen, 0
bind = , M,       fullscreen, 1
bind = , P,       pseudo,
bind = , S,       layoutmsg, togglesplit

bind = , Escape, submap, reset
submap = reset
### END WINDOW

### SYSTEM
bindu = Super, S, submap, system
submap = system, reset

bind = , L, exec, $s/lg.sh
bind = , R, exec, $s/reload.sh

bind = Shift, Delete, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

bind = , Escape, submap, reset
submap = reset
### END SYSTEM

bind = Super, H, movefocus, l
bind = Super, J, movefocus, d
bind = Super, K, movefocus, u
bind = Super, L, movefocus, r

bind = Super Shift, H, movewindow, l 20
bind = Super Shift, J, movewindow, d 20
bind = Super Shift, K, movewindow, u 20
bind = Super Shift, L, movewindow, r 20

binde = Super Ctrl, H, resizeactive, -20 0
binde = Super Ctrl, J, resizeactive, 0 20
binde = Super Ctrl, K, resizeactive, 0 -20
binde = Super Ctrl, L, resizeactive, 20 0

bind = Super, 1, workspace, 1
bind = Super, 2, workspace, 2
bind = Super, 3, workspace, 3
bind = Super, 4, workspace, 4
bind = Super, 5, workspace, 5
bind = Super, 6, workspace, 6
bind = Super, 7, workspace, 7
bind = Super, 8, workspace, 8
bind = Super, 9, workspace, 9
bind = Super, 0, workspace, 10

bind = Super Shift, 1, movetoworkspace, 1
bind = Super Shift, 2, movetoworkspace, 2
bind = Super Shift, 3, movetoworkspace, 3
bind = Super Shift, 4, movetoworkspace, 4
bind = Super Shift, 5, movetoworkspace, 5
bind = Super Shift, 6, movetoworkspace, 6
bind = Super Shift, 7, movetoworkspace, 7
bind = Super Shift, 8, movetoworkspace, 8
bind = Super Shift, 9, movetoworkspace, 9
bind = Super Shift, 0, movetoworkspace, 10

bindu = Super, mouse_down, workspace, e+1
bindu = Super, mouse_up, workspace, e-1

binde = Super, Tab, workspace, e+1
binde = Super Shift, Tab, workspace, e-1

bindum = Super, mouse:272, movewindow
bindum = Super, mouse:273, resizewindow

binduel = , XF86AudioRaiseVolume,  exec, $s/vol.sh up
binduel = , XF86AudioLowerVolume,  exec, $s/vol.sh down
binduel = , XF86AudioMute,         exec, $s/vol.sh mute
binduel = , XF86AudioMicMute,      exec, $s/vol.sh mic-mute
binduel = , XF86MonBrightnessUp,   exec, $s/bl.sh up
binduel = , XF86MonBrightnessDown, exec, $s/bl.sh down

bindul = , XF86AudioNext,  exec, playerctl next
bindul = , XF86AudioPause, exec, playerctl play-pause
bindul = , XF86AudioPlay,  exec, playerctl play-pause
bindul = , XF86AudioPrev,  exec, playerctl previous
bindul = Super Alt, N, exec, playerctl next
bindul = Super Alt, P, exec, playerctl play-pause
bindul = Super Alt, B, exec, playerctl previous

