general {
  resize_on_border = false
  layout = dwindle
}

dwindle {
  pseudotile = true
  preserve_split = true
}

master {
  new_status = master
}

windowrule {
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}

misc {
  enable_swallow          = true
  swallow_regex           = ^(foot)$
  swallow_exception_regex = ^(wev.*)$
}

windowrule = match:class ^brave-browser$, workspace 1
windowrule = match:class ^spotify$,       workspace 9
windowrule = match:class ^vesktop$,       workspace 10

windowrule = match:class ^imv$,   opacity 1.0 override
windowrule = match:class ^mpv$,   opacity 1.0 override
windowrule = match:class ^sober$, opacity 1.0 override
windowrule = match:class ^brave-browser$, match:title ^(.*)(Y|y)ou(T|t)ube(.*)$, opacity 1.0 override

layerrule = match:namespace menu,          ignore_alpha 0, blur on
layerrule = match:namespace notifications, ignore_alpha 0, blur on
